/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Column: typeof import('./components/Column.vue')['default']
    ColumnDouble: typeof import('./components/ColumnDouble.vue')['default']
    Line: typeof import('./components/Line.vue')['default']
  }
}
